apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /web
          backend:
            serviceName: web-service
            servicePort: 3000
#         # - path: /banana
#         #   backend:
#         #     serviceName: banana-service
#         #     servicePort: 5678

# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: test-ingress
# spec:
#   backend:
#     serviceName: web-service
#     servicePort: 3000
