---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30013
  # clusterIP: 10.0.171.239
  type: LoadBalancer
  externalIPs:
  - 192.168.0.10

# status:
#   loadBalancer:
#     ingress:
#     - ip: 192.0.2.127
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        # env:
        # - name: POD_NAME
        #   valueFrom:
        #     fieldRef:
        #       apiVersion: v1
        #       fieldPath: metadata.name
        ports:
        - containerPort: 8080
        name: nginx
