version: '3.7'
services:
  web:
    # build: './web'
    # ports:
    #   - "3000:3000"
    image: ioannispapakonstantinou/micro_web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M

  search:
    # build: './search'
    # ports:
    #   - "3001:3000"
    #   - "3005:3000"
    image: ioannispapakonstantinou/micro_search
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.80'
        #   memory: 50M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M


  books:
    # build: './books'
    # ports:
    #   - "3002:3000"
    image: ioannispapakonstantinou/micro_books
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.20'
          # memory: 50M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M

  videos:
    # build: './videos'
    image: ioannispapakonstantinou/micro_videos
    # ports:
    #   - "3003:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M

  db:
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - books
      - search
      - videos
    deploy:
      placement:
        constraints: [node.role == manager]
