apiVersion: v1
kind: Service
metadata:
  name: web-mongo
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
  selector:
    app: mongo
    tier: mongodb
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: web-mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
        tier: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        env:
        - name: MONGO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-pass
              key: password
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /var/lib/mongodb
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
