apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: search
  name: search
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: search
    spec:
      containers:
      - env:
        - name: MONGO_DB_URI
          value: mongodb://db/microservices
        image: search
        name: search
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
